"""add roles and nullable role_id

Revision ID: 5713c3360823
Revises: d4b7ba48e649
Create Date: 2026-04-28 20:14:37.913150

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5713c3360823'
down_revision: str | Sequence[str] | None = 'd4b7ba48e649'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###

    # --- ADD THIS CUSTOM CODE TO SEED THE DATABASE ---
    # 1. Insert the default roles
    op.execute("INSERT INTO roles (id, name, description) VALUES (1, 'user', 'Standard user')")
    op.execute("INSERT INTO roles (id, name, description) VALUES (2, 'admin', 'System administrator')")

    # 2. Update all existing users to have role_id = 1
    op.execute("UPDATE users SET role_id = 1")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###
