"""set role_id not nullable and set default to 1

Revision ID: 88cbb9a8ec1b
Revises: 5713c3360823
Create Date: 2026-04-28 20:19:44.451568

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '88cbb9a8ec1b'
down_revision: str | Sequence[str] | None = '5713c3360823'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               server_default=None)
    # ### end Alembic commands ###
